/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    IMdiDouban: typeof import('~icons/mdi/douban')['default']
    IMdiWikipedia: typeof import('~icons/mdi/wikipedia')['default']
    KButton: typeof import('@0x-jerry/vue-kit')['KButton']
    KInput: typeof import('@0x-jerry/vue-kit')['KInput']
    Tag: typeof import('./components/Tag.vue')['default']
  }
}
