// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    IMdiDouban: typeof import('~icons/mdi/douban')['default']
    IMdiWikipedia: typeof import('~icons/mdi/wikipedia')['default']
    KButton: typeof import('@0x-jerry/vue-kit')['KButton']
    KInput: typeof import('@0x-jerry/vue-kit')['KInput']
    Tag: typeof import('./components/Tag.vue')['default']
  }
}
